### ISSUE TITLE
Better error message if search limit exceeded

### ISSUE THREAD

**Issue by ygrek** [SKS-Keyserver/sks-keyserver#43]
**[Original report](https://bitbucket.org/skskeyserver/sks-keyserver/issue/43) by Dmitry Bolshakov (Bitbucket: [bdimych](https://bitbucket.org/bdimych), GitHub: [bdimych](https://github.com/bdimych)).**

----------------------------------------

http://zimmermann.mayfirst.org:11371/pks/lookup?search=Bitcoin&op=vindex  
"Error handling request. Exception raised."

http://zimmermann.mayfirst.org:11371/pks/lookup?search=Bitcoin+Core&op=vindex  
results displayed

I asked  
http://security.stackexchange.com/questions/135197/gpg-server-hides-search-results  
and decided to write this bug - why not just print clear message "limit exceeded" ?

**Comment by wiml** [comment]
It looks like the problem is just the scope of the `try ... with` block in `handle_get_request` in `dbserver.ml`. There is code there to translate the exception into a clearer error message, but the exception is thrown a few lines before the `try`, and so it doesn't get caught.

**Comment by ygrek** [comment]
thanks
