### ISSUE TITLE
Update KeydumpSources wiki entry

### ISSUE THREAD

**Issue by MarcelWaldvogel** [SKS-Keyserver/sks-keyserver#85]
The KeydumpSources is out of date. Could you please change the following (if there were PRs for wiki entries, I would do that):

* The keydump size is now around 14 GB, no longer 4 GB
* The following dumps no longer seem to exist
   * https://keyserver.mattrude.com/dump/ and ftp://keyserver.mattrude.com/
* The following dumps no longer seem to be updated
   * http://stueve.us/keydump/ (last dump from April 2019, also seems to be incomplete)
   * https://pgp.key-server.io/sks-dump/ (last dump from January 2021; contacted the operator last week, have not heard back, so do not know whether it will resume)
* The following additional dump is available (in addition to niif, dumain, and cyberbits, which are current and available)
   * https://keywin.trifence.ch/dumps/ (monthly dump plus daily incrementals at midnight UTC)

**Comment by christmart** [comment]
You could also add https://pgp.uni-mainz.de/dump/

**Comment by ygrek** [comment]
updated, thanks!

I shall probably just move docs to the repository as .md files (github will render them properly) :thinking:
