### ISSUE TITLE
pool.sks-keyservers.net not found

### ISSUE THREAD

**Issue by ipantovic** [SKS-Keyserver/sks-keyserver#87]
Hi,

this is not bug per se however it is an issue
it seems that DNS records expired or are unmaintained and pool.sks-keyservers.net can't be found at SOA NS:

~# host -t soa sks-keyservers.net
sks-keyservers.net has SOA record ns2.kfwebs.net. kf.kfwebs.net. 3210622136 600 14400 172800 600
~# host pool.sks-keyservers.net ns2.kfwebs.net.
Using domain server:
Name: ns2.kfwebs.net.
Address: 37.191.231.105#53
Aliases:

Host pool.sks-keyservers.net not found: 3(NXDOMAIN)

any info on the above?

**Comment by ygrek** [comment]
there is discussion in https://lists.nongnu.org/archive/html/sks-devel/2021-06/msg00001.html
